# Declare testing language
language: php

# Language versioning
php:
  - 5.4

# Envars for contextual operations
env:
  - DB=mysql UPGRADE=none
  - DB=postgres UPGRADE=none

# Specifications of database(s)
mysql:
  adapter: mysql2
  database: drupal_db
  username: root
  encoding: utf8
postgres:
  adapter: postgresql
  database: drupal_db
  username: postgres

# Travis scripts
install:
  - sudo apt-get update > /dev/null
  - if [[ "$DB" == "pgsql" ]]; then psql -c 'create database drupal_db;' -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e 'create database IF NOT EXISTS drupal_db;'; fi

  # Install latest Drush 6.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --no-interaction drush/drush:6.*

  # Build Behat dependencies
  - cd ./tests/behat
  - composer install --no-interaction
  # - cp behat.template.yml behat.local.yml
  - cd ../../../

  # Build Codebase
  - mkdir private_files
  - mkdir profiles
  - mv wet-boew-drupal wetkit
  - mv wetkit profiles/
  - mkdir drupal
  - mv profiles drupal/

  # Test the current branch
  - cd drupal
  - drush make --yes profiles/wetkit/drupal-org-core.make --prepare-install
  - drush make --yes profiles/wetkit/drupal-org.make --no-core --contrib-destination=profiles/wetkit
  - cd ../

  # Download an old version to test upgrading from.
  - if [[ "$UPGRADE" != none ]]; then drush dl wetkit-$UPGRADE; fi

  # Setup files
  - sudo chmod -R 777 drupal/sites/all

  # Setup display for Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # Get Selenium
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.37.0.jar
  - java -jar selenium-server-standalone-2.37.0.jar > /dev/null 2>&1 &
  - sleep 5

  # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  # Do the site install (either the current revision or old for the upgrade).
  - if [[ "$UPGRADE" == none ]]; then cd drupal; else cd wetkit-$UPGRADE; fi
  - if [[ "$DB" == "postgres" ]]; then drush si wetkit wetkit_theme_selection_form.theme=wetkit_omega install_configure_form.demo_content=TRUE --sites-subdir=default --db-url=pgsql://postgres:@127.0.0.1:5432/drupal_db --account-name=admin --account-pass=WetKit@2012 --site-mail=admin@example.com --site-name='Web Experience Toolkit' --yes; fi
  - if [[ "$DB" == "mysql" ]]; then drush si wetkit wetkit_theme_selection_form.theme=wetkit_omega install_configure_form.demo_content=TRUE --sites-subdir=default --db-url=mysql://root:@127.0.0.1:3306/drupal_db --account-name=admin --account-pass=WetKit@2012 --site-mail=admin@example.com --site-name='Web Experience Toolkit' --yes; fi
  - drush cc all
  - cd ../drupal

  # If we're an upgrade test, run the upgrade process.
  - if [[ "$UPGRADE" != none ]]; then cp -a ../wetkit-$UPGRADE/sites/default/* sites/default/ && drush updb --yes; fi

  # Run the server
  - drush runserver --server=builtin 8080 > /dev/null 2>&1 &
  - sleep 10
  - cd profiles/wetkit/tests/behat

script:
  - ./bin/behat --config behat.travis.yml
